# -*- coding: utf-8 -*-
"""Medical_QA_QLoRA_A100_v3 (2) (1) (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wv4F4xwoVEH-o8I-i0pelFr-5Zf1KxT

---
## ⚙️ Section 1 — Install Dependencies (A100-Safe)

This cell auto-detects your CUDA version and PyTorch version and installs the **exact correct Unsloth wheel** for your environment — the most common source of import errors.
"""

import subprocess, sys, importlib

# ══════════════════════════════════════════════════════════════════════════════
# UNSLOTH INSTALLATION — Lightning AI / Colab / Kaggle / Local
#
# Strategy:
#   1. If unsloth already importable (e.g. pre-installed in cloudspace) → skip
#   2. If PyTorch already installed  → plain `pip install unsloth` (safest)
#   3. If bare environment          → install torch first, then unsloth
#
# We NEVER build flash-attn from source — it's pre-installed on A100 instances
# or skipped entirely (Unsloth works fine without it via xformers fallback).
# ══════════════════════════════════════════════════════════════════════════════

def run(cmd, **kwargs):
    """Run a pip command, print output on failure."""
    result = subprocess.run(cmd, capture_output=True, text=True, **kwargs)
    if result.returncode != 0:
        print("STDOUT:", result.stdout[-3000:])
        print("STDERR:", result.stderr[-3000:])
        raise RuntimeError(f"Command failed: {' '.join(cmd)}")
    return result

# ── 1. Check if unsloth is already installed ────────────────────────────────
try:
    import unsloth
    print(f"✅ Unsloth already installed: {unsloth.__version__} — skipping install")
except ImportError:
    print("Unsloth not found — installing...")

    # ── 2. Check if torch is already installed ───────────────────────────────
    try:
        import torch
        torch_available = True
        cuda_ver = torch.version.cuda or "cpu"
        print(f"   PyTorch {torch.__version__} detected (CUDA {cuda_ver})")
    except ImportError:
        torch_available = False
        print("   PyTorch not found — will install first")

    if not torch_available:
        # Bare environment: install PyTorch for CUDA 12.4 (A100 default)
        print("   Installing PyTorch + CUDA 12.4...")
        run([sys.executable, "-m", "pip", "install", "-q",
             "torch", "torchvision", "torchaudio",
             "--index-url", "https://download.pytorch.org/whl/cu124"])
        import torch

    # ── 3. Detect CUDA + torch version to pick correct unsloth extra ─────────
    import torch as _torch
    cuda_str   = (_torch.version.cuda or "12.4").replace(".", "")[:4]   # "12.4" → "124"
    tv         = _torch.__version__.split("+")[0].split(".")             # ["2","4","0"]
    torch_str  = tv[0] + tv[1] + (tv[2][0] if len(tv) > 2 else "0")    # "240"

    cuda_key  = f"cu{cuda_str}"     # e.g. cu124
    torch_key = f"torch{torch_str}" # e.g. torch240

    # Valid extras from unsloth 2026.4.8 PyPI metadata
    # Format: cu{cuda}onlytorch{torch}
    VALID_EXTRAS = {
        ("cu118", "torch211"), ("cu121", "torch211"),
        ("cu118", "torch212"), ("cu121", "torch212"),
        ("cu118", "torch220"), ("cu121", "torch220"),
        ("cu118", "torch230"), ("cu121", "torch230"),
        ("cu118", "torch240"), ("cu121", "torch240"),
        ("cu118", "torch250"), ("cu121", "torch250"), ("cu124", "torch250"),
        ("cu118", "torch251"), ("cu121", "torch251"), ("cu124", "torch251"),
        ("cu118", "torch260"), ("cu124", "torch260"), ("cu126", "torch260"),
        ("cu118", "torch270"), ("cu126", "torch270"), ("cu128", "torch270"),
        ("cu118", "torch271"), ("cu126", "torch271"), ("cu128", "torch271"),
        ("cu118", "torch280"), ("cu126", "torch280"), ("cu128", "torch280"), ("cu130", "torch280"),
        ("cu126", "torch290"), ("cu128", "torch290"), ("cu130", "torch290"),
        ("cu126", "torch291"), ("cu128", "torch291"), ("cu130", "torch291"),
        ("cu126", "torch2100"), ("cu128", "torch2100"), ("cu130", "torch2100"),
    }

    # CUDA fallback map: if exact CUDA not in table, pick nearest supported
    CUDA_FALLBACK = {
        "cu117": "cu118", "cu119": "cu121", "cu120": "cu121",
        "cu122": "cu121", "cu123": "cu121",
        "cu124": "cu124", "cu125": "cu126", "cu127": "cu128",
        "cu129": "cu130", "cu131": "cu130",
    }

    # Torch fallback map: if exact torch not in table, pick nearest supported
    TORCH_FALLBACK_ORDER = [
        "torch211","torch212","torch220","torch230","torch240",
        "torch250","torch251","torch260","torch270","torch271",
        "torch280","torch290","torch291","torch2100"
    ]

    # Resolve CUDA key
    ck = CUDA_FALLBACK.get(cuda_key, cuda_key)
    if not any(ck == c for c, _ in VALID_EXTRAS):
        # Last resort: pick cu126 (widely supported mid-range)
        ck = "cu126"

    # Resolve torch key — try exact, then step down
    tk = torch_key
    if not any(tk == t for _, t in VALID_EXTRAS):
        for candidate in reversed(TORCH_FALLBACK_ORDER):
            if (ck, candidate) in VALID_EXTRAS:
                tk = candidate
                break

    extra = f"{ck}only{tk}"
    if (ck, tk) in VALID_EXTRAS:
        install_spec = f"unsloth[{extra}]"
    else:
        # If nothing matched, fall back to plain unsloth (works when torch pre-installed)
        install_spec = "unsloth"

    print(f"   Resolved install spec: {install_spec}")

    # ── 4. Install unsloth ───────────────────────────────────────────────────
    try:
        run([sys.executable, "-m", "pip", "install", "-q", install_spec])
        print(f"   ✅ Installed via extra [{extra}]")
    except RuntimeError:
        print(f"   ⚠️  Extra install failed — falling back to plain `pip install unsloth`")
        run([sys.executable, "-m", "pip", "install", "-q", "unsloth"])
        print(f"   ✅ Installed via plain unsloth")

# ── 5. Install supporting packages ──────────────────────────────────────────
# --no-deps prevents overwriting versions unsloth carefully selected
print("\nInstalling trl / peft / accelerate / bitsandbytes ...")
run([sys.executable, "-m", "pip", "install", "-q", "--no-deps",
     "trl>=0.12.0",
     "peft>=0.13.0",
     "accelerate>=0.34.0",
     "bitsandbytes>=0.43.0",
])

# ── 6. Install data utilities ────────────────────────────────────────────────
run([sys.executable, "-m", "pip", "install", "-q",
     "datasets>=2.20.0",
     "huggingface_hub",
     "sentencepiece",
     "protobuf",
     "scipy",
     "scikit-learn",
     "seaborn",
     "matplotlib",
])

print("\n✅ All dependencies ready!")

# ── Verify everything imported cleanly ──────────────────────────────────────
import torch

assert torch.cuda.is_available(), '⚠️  No GPU found. Runtime → Change runtime type → A100'

gpu_name   = torch.cuda.get_device_name(0)
gpu_memory = torch.cuda.get_device_properties(0).total_memory / 1e9
print(f'GPU        : {gpu_name}')
print(f'VRAM       : {gpu_memory:.1f} GB')
print(f'CUDA       : {torch.version.cuda}')
print(f'PyTorch    : {torch.__version__}')
print(f'BF16 OK?   : {torch.cuda.is_bf16_supported()}')

import unsloth
print(f'Unsloth    : {unsloth.__version__}')

import trl, peft, transformers
print(f'TRL        : {trl.__version__}')
print(f'PEFT       : {peft.__version__}')
print(f'Transformers: {transformers.__version__}')
print('\n✅ All imports OK!')

"""---
## 📦 Section 3 — Load & Explore Datasets
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import warnings
warnings.filterwarnings('ignore')

from datasets import load_dataset, Dataset, concatenate_datasets

pd.set_option('display.max_colwidth', 120)
print('✅ Libraries loaded')

print('Loading Dataset 1: medalpaca/medical_meadow_medqa ...')
ds1 = load_dataset('medalpaca/medical_meadow_medqa', split='train')
df1 = ds1.to_pandas()
print(f'\n📊 Shape: {df1.shape}')
print(f'   Columns: {list(df1.columns)}')
df1.head(2)

print('Loading Dataset 2: keivalya/MedQuad-MedicalQnADataset ...')
ds2 = load_dataset('keivalya/MedQuad-MedicalQnADataset', split='train')
df2 = ds2.to_pandas()
print(f'\n📊 Shape: {df2.shape}')
print(f'   Columns: {list(df2.columns)}')
df2.head(2)

"""---
## 🧹 Section 4 — Data Cleaning & EDA

### Critical Fix — MedAlpaca MCQ Format

MedAlpaca stores USMLE-style questions in `input` like:
```
A 45-year-old male presents with chest pain...
A) Aspirin
B) Metoprolol   ← these options appear in training but NOT at inference
C) Nitroglycerin
D) Heparin
```
And `output` like: `"The answer is (C). Nitroglycerin works by..."`

**Problem:** At inference you pass a clean question without options → train/inference distribution mismatch → garbage output.  
**Fix:** Strip MCQ options from questions, strip answer-letter prefix from answers.
"""

def clean_text(text):
    """Universal text cleaner."""
    if not isinstance(text, str):
        return None
    text = text.strip()
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'\\n|\\t', ' ', text)
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text if len(text) > 10 else None


def strip_mcq_options(text):
    """
    Remove MCQ option lines like:
      A) option text
      (B) option text
      A. option text
    from the question body so inference distribution matches training.
    """
    if not isinstance(text, str):
        return text
    # Remove lines that start with option labels
    text = re.sub(r'\b[A-E][\)\.]\s+[^\n]+', '', text)
    text = re.sub(r'\([A-E]\)\s+[^\n]+', '', text)
    return re.sub(r'\s+', ' ', text).strip()


def strip_answer_prefix(text):
    """
    Remove USMLE-style answer letter prefix:
      'The answer is (C). ...' → '...'
      'C) ...'                 → '...'
    """
    if not isinstance(text, str):
        return text
    text = re.sub(r'^(The correct answer is|The answer is|Answer:)\s*\(?[A-E]\)?[\s\.\-:]*', '', text, flags=re.IGNORECASE)
    text = re.sub(r'^[A-E][\)\.]\s*', '', text)
    return text.strip()


def clean_medalpaca(df):
    df = df.copy()

    # 'input' = question body (may include MCQ options), 'output' = answer
    if 'input' not in df.columns or 'output' not in df.columns:
        raise ValueError("Expected 'input' and 'output' columns")

    df = df.rename(columns={'input': 'question', 'output': 'answer'})[['question', 'answer']]

    df['question'] = df['question'].apply(clean_text).apply(strip_mcq_options)
    df['answer']   = df['answer'].apply(clean_text).apply(strip_answer_prefix)

    df = df.dropna(subset=['question', 'answer'])
    df['question'] = df['question'].astype(str)
    df['answer']   = df['answer'].astype(str)

    df = df[df['question'].str.len() >= 30]  # must be a real question
    df = df[df['answer'].str.len()   >= 40]  # must have real explanation
    df = df[df['answer'].str.len()   <= 4000]
    df = df.drop_duplicates(subset=['question'])

    df['source'] = 'medalpaca_medqa'
    return df.reset_index(drop=True)


df1_clean = clean_medalpaca(df1)
print(f'✅ MedAlpaca  — Before: {len(df1):,} | After: {len(df1_clean):,}')

# Spot-check: verify options are removed
print('\n--- Question sample (options should be gone) ---')
print(df1_clean.iloc[0]['question'][:200])
print('\n--- Answer sample (letter prefix should be gone) ---')
print(df1_clean.iloc[0]['answer'][:200])

def clean_medquad(df):
    df = df.copy()
    df.columns = [c.lower() for c in df.columns]

    q_col = next((c for c in df.columns if 'question' in c or 'query' in c), None)
    a_col = next((c for c in df.columns if 'answer' in c or 'response' in c), None)

    if not q_col or not a_col:
        raise ValueError(f'Could not find Q/A columns. Available: {list(df.columns)}')

    df = df[[q_col, a_col]].rename(columns={q_col: 'question', a_col: 'answer'})

    df['question'] = df['question'].apply(clean_text)
    df['answer']   = df['answer'].apply(clean_text)

    df = df.dropna(subset=['question', 'answer'])
    df['question'] = df['question'].astype(str)
    df['answer']   = df['answer'].astype(str)

    df = df[df['question'].str.len() >= 20]
    df = df[df['answer'].str.len()   >= 50]
    df = df[df['answer'].str.len()   <= 4000]
    df = df.drop_duplicates(subset=['question'])

    df['source'] = 'medquad_nih'
    return df.reset_index(drop=True)


df2_clean = clean_medquad(df2)
print(f'✅ MedQuad NIH — Before: {len(df2):,} | After: {len(df2_clean):,}')

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle('Medical Q&A Dataset EDA (v3 — cleaned)', fontsize=16, fontweight='bold')

colors   = ['#4A90D9', '#E97040']
datasets_info = [(df1_clean, 'MedAlpaca MedQA (MCQ stripped)', 0),
                 (df2_clean, 'MedQuad NIH', 1)]

for df, name, idx in datasets_info:
    q_lens = df['question'].str.len()
    a_lens = df['answer'].str.len()

    axes[idx][0].hist(q_lens, bins=40, color=colors[idx], alpha=0.8, edgecolor='white')
    axes[idx][0].set_title(f'{name}\nQuestion Length')
    axes[idx][0].axvline(q_lens.median(), color='red', linestyle='--',
                         label=f'Median: {q_lens.median():.0f}')
    axes[idx][0].legend()

    axes[idx][1].hist(a_lens, bins=40, color=colors[idx], alpha=0.8, edgecolor='white')
    axes[idx][1].set_title(f'{name}\nAnswer Length')
    axes[idx][1].axvline(a_lens.median(), color='red', linestyle='--',
                         label=f'Median: {a_lens.median():.0f}')
    axes[idx][1].legend()

    stats = {
        'Total Samples': len(df),
        'Avg Q Length':  f'{q_lens.mean():.0f} chars',
        'Avg A Length':  f'{a_lens.mean():.0f} chars',
        'Max Q Length':  f'{q_lens.max():.0f} chars',
        'Max A Length':  f'{a_lens.max():.0f} chars',
    }
    axes[idx][2].axis('off')
    table = axes[idx][2].table(
        cellText=[[k, v] for k, v in stats.items()],
        colLabels=['Metric', 'Value'],
        loc='center', cellLoc='left'
    )
    table.auto_set_font_size(False)
    table.set_fontsize(11)
    table.scale(1.4, 2)
    axes[idx][2].set_title(f'{name}\nStatistics')

plt.tight_layout()
plt.savefig('dataset_eda_v3.png', dpi=120, bbox_inches='tight')
plt.show()
print('📈 EDA complete!')

!pip install wordcloud

from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import re

# ── Custom medical stopwords ──────────────────────────────────────────────────
MEDICAL_STOPWORDS = STOPWORDS | {
    'patient', 'patients', 'may', 'also', 'one', 'two', 'used', 'use',
    'can', 'often', 'common', 'include', 'including', 'however', 'well',
    'associated', 'condition', 'conditions', 'treatment', 'treatments',
    'disorder', 'disease', 'symptoms', 'symptom', 'cause', 'caused',
    'occur', 'occurs', 'typically', 'usually', 'known', 'called',
    'type', 'types', 'form', 'forms', 'refers', 'term', 'result',
}

def clean_for_wordcloud(text_series):
    text = ' '.join(text_series.dropna().astype(str))
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    text = re.sub(r'\b\w{1,3}\b', '', text)   # drop very short words
    text = re.sub(r'\s+', ' ', text).strip()
    return text.lower()

def make_wc(text, colormap, stopwords=MEDICAL_STOPWORDS):
    return WordCloud(
        width=800, height=400,
        background_color='white',
        colormap=colormap,
        stopwords=stopwords,
        max_words=120,
        collocations=True,          # keeps bigrams like "blood pressure"
        collocation_threshold=10,
        min_font_size=10,
        prefer_horizontal=0.85,
    ).generate(text)


# ── Build corpora ─────────────────────────────────────────────────────────────
q_text  = clean_for_wordcloud(df_combined['question'])
a_text  = clean_for_wordcloud(df_combined['answer'])

# Per-source (optional but useful)
src1_text = clean_for_wordcloud(df_combined[df_combined['source'] == 'medalpaca_medqa']['question'])
src2_text = clean_for_wordcloud(df_combined[df_combined['source'] == 'medquad_nih']['question'])


# ── Plot ──────────────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(18, 12))
fig.suptitle('Medical Q&A — Word Cloud Analysis', fontsize=15, fontweight='bold', y=0.98)

gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.35, wspace=0.1)

panels = [
    (gs[0, 0], make_wc(q_text,   'Blues'),   'Questions — all sources'),
    (gs[0, 1], make_wc(a_text,   'Oranges'), 'Answers — all sources'),
    (gs[1, 0], make_wc(src1_text,'PuBu'),    'Questions — MedAlpaca MedQA'),
    (gs[1, 1], make_wc(src2_text,'YlOrBr'),  'Questions — MedQuad NIH'),
]

for spec, wc, title in panels:
    ax = fig.add_subplot(spec)
    ax.imshow(wc, interpolation='bilinear')
    ax.axis('off')
    ax.set_title(title, fontsize=12, fontweight='bold', pad=8)

plt.savefig('wordclouds.png', dpi=130, bbox_inches='tight')
plt.show()
print('✅ Saved: wordclouds.png')

"""---
## 🔀 Section 5 — Merge & Format for Instruction Tuning

Both datasets are now in clean natural-language Q&A format (no MCQ options).  
`MAX_SEQ_LEN = 2048` — A100 has 80GB, use it.
"""

from sklearn.model_selection import train_test_split

df_combined = pd.concat([df1_clean, df2_clean], ignore_index=True)
df_combined = df_combined.drop_duplicates(subset=['question'])
df_combined = df_combined.sample(frac=1, random_state=42).reset_index(drop=True)

print(f'📊 Combined size : {len(df_combined):,}')
print(f'   Source split  :')
print(df_combined['source'].value_counts().to_string())

# ── Mistral Instruct chat template ──────────────────────────────────────────
SYSTEM_PROMPT = (
    'You are a knowledgeable and compassionate medical assistant. '
    'Provide accurate, evidence-based answers to medical questions. '
    'Always recommend consulting a qualified healthcare professional for '
    'personal medical advice, diagnosis, or treatment.'
)

def format_mistral_chat(row):
    question = row['question'].strip()
    answer   = row['answer'].strip()
    return (
        f'<s>[INST] {SYSTEM_PROMPT}\n\n'
        f'Question: {question} [/INST] '
        f'{answer}</s>'
    )

df_combined['text'] = df_combined.apply(format_mistral_chat, axis=1)

# ── Token filter: 1 token ≈ 4 chars — but use 3.5 for safety (avoids under-counting)
df_combined['est_tokens'] = df_combined['text'].str.len() / 3.5

MAX_TOKENS = 1500  # generous — real max_seq_length is 2048 tokens
before = len(df_combined)
df_combined = df_combined[df_combined['est_tokens'] <= MAX_TOKENS]
print(f'\n📏 After token filter (<{MAX_TOKENS} est tokens): {len(df_combined):,} / {before:,}')
print(f'   Mean  : {df_combined["est_tokens"].mean():.0f} tokens')
print(f'   Median: {df_combined["est_tokens"].median():.0f} tokens')
print(f'   Max   : {df_combined["est_tokens"].max():.0f} tokens')

df_train, df_val = train_test_split(df_combined, test_size=0.05, random_state=42)

# A100 can handle all data — no artificial cap
# Remove the TRAIN_SAMPLE_LIMIT if you had one before
print(f'Train : {len(df_train):,}')
print(f'Val   : {len(df_val):,}')

train_dataset = Dataset.from_pandas(df_train[['text']].reset_index(drop=True))
val_dataset   = Dataset.from_pandas(df_val[['text']].reset_index(drop=True))

print('\n--- Sample formatted text ---')
print(train_dataset[0]['text'][:500], '...')

"""---
## 🤖 Section 6 — Load Model with Unsloth (Full BF16, A100)

**A100 config:**
- `load_in_4bit = False` — full BF16, 80GB VRAM is enough for Mistral-7B
- `lora_alpha = r` — do **not** set alpha > r in full precision, it over-scales updates
- `lora_dropout = 0.0` — Unsloth's fused kernels are optimised for dropout=0
- `use_rslora = True` — rank-stabilized LoRA, significantly more stable at r=64
"""

from unsloth import FastLanguageModel
import torch

MODEL_NAME   = 'mistralai/Mistral-7B-Instruct-v0.2'
MAX_SEQ_LEN  = 2048   # A100: plenty of VRAM for 2048
LOAD_IN_4BIT = False  # A100-80GB: full BF16, no quantisation needed

print(f'🔄 Loading: {MODEL_NAME}')
print('   Downloading ~14GB on first run ...')

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name     = MODEL_NAME,
    max_seq_length = MAX_SEQ_LEN,
    dtype          = torch.bfloat16,   # Explicit BF16 for A100
    load_in_4bit   = LOAD_IN_4BIT,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token    = tokenizer.eos_token
    tokenizer.pad_token_id = tokenizer.eos_token_id

print(f'\n✅ Base model loaded!')
print(f'   Type  : {type(model).__name__}')
print(f'   VRAM  : {torch.cuda.memory_allocated()/1e9:.1f} GB used')

LORA_RANK = 64  # High rank — A100 can afford it

model = FastLanguageModel.get_peft_model(
    model,
    r              = LORA_RANK,
    lora_alpha     = LORA_RANK,          # FIX: alpha == r, not 2×r
    lora_dropout   = 0.0,                # FIX: 0.0 is the Unsloth-optimised path
    bias           = 'none',
    target_modules = [
        'q_proj', 'k_proj', 'v_proj', 'o_proj',
        'gate_proj', 'up_proj', 'down_proj',
    ],
    use_gradient_checkpointing = 'unsloth',  # Unsloth VRAM-saving checkpointing
    use_rslora     = True,               # FIX: rank-stabilized LoRA, stable at r=64
    random_state   = 42,
    loftq_config   = None,
)

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total     = sum(p.numel() for p in model.parameters())
print(f'✅ LoRA adapters applied!')
print(f'   Rank            : {LORA_RANK}  (RSLoRA)')
print(f'   Trainable params: {trainable:,}  ({100*trainable/total:.2f}%)')
print(f'   Total params    : {total:,}')
print(f'   VRAM after LoRA : {torch.cuda.memory_allocated()/1e9:.1f} GB')

"""---
## 🏋️ Section 7 — Fine-Tuning with SFTTrainer

**A100 config highlights:**
- `packing = True` — packs multiple short sequences into one → 3–4× more tokens per step
- `per_device_train_batch_size = 8` + `gradient_accumulation_steps = 4` → effective batch = 32
- `learning_rate = 2e-4` — standard for LoRA; works with RSLoRA
- `warmup_ratio = 0.03` — short warmup for 3-epoch run
"""

from trl import SFTTrainer, SFTConfig
import os

OUTPUT_DIR = './medical_qa_mistral_lora_v3'
os.makedirs(OUTPUT_DIR, exist_ok=True)

sft_config = SFTConfig(
    output_dir             = OUTPUT_DIR,
    dataset_text_field     = 'text',
    max_seq_length         = MAX_SEQ_LEN,  # 2048

    # ── KEY FIX: packing=True packs short sequences together ────────────────
    # Eliminates padding waste → 3-4x more real tokens per step on A100
    packing                = True,

    # ── Batch config (A100-80GB) ─────────────────────────────────────────────
    per_device_train_batch_size  = 8,    # effective batch = 8 × 4 = 32
    per_device_eval_batch_size   = 4,
    gradient_accumulation_steps  = 4,
    num_train_epochs             = 3,

    # ── Learning rate ────────────────────────────────────────────────────────
    learning_rate       = 2e-4,          # Standard for LoRA; safe with RSLoRA
    lr_scheduler_type   = 'cosine',
    warmup_ratio        = 0.03,          # ~90 steps warmup for 3 epochs
    weight_decay        = 0.01,

    # ── Precision (A100 → always BF16) ──────────────────────────────────────
    bf16                = True,
    fp16                = False,

    # ── Optimizer ────────────────────────────────────────────────────────────
    optim               = 'adamw_8bit',  # Unsloth's fused 8-bit AdamW
    dataloader_num_workers = 4,          # A100 instance has CPU cores to spare

    # ── Logging & saving ─────────────────────────────────────────────────────
    logging_steps       = 10,
    eval_strategy       = 'steps',
    eval_steps          = 50,
    save_strategy       = 'steps',
    save_steps          = 50,
    save_total_limit    = 3,
    load_best_model_at_end   = True,
    metric_for_best_model    = 'eval_loss',

    report_to           = 'none',        # Switch to 'wandb' for experiment tracking
    remove_unused_columns = True,
    seed                = 42,
)

print('✅ SFTConfig ready')
steps_per_epoch = len(train_dataset) // (
    sft_config.per_device_train_batch_size * sft_config.gradient_accumulation_steps
)
print(f'   Effective batch size : {sft_config.per_device_train_batch_size * sft_config.gradient_accumulation_steps}')
print(f'   Steps per epoch      : ~{steps_per_epoch}')
print(f'   Total steps (est)    : ~{steps_per_epoch * sft_config.num_train_epochs}')

trainer = SFTTrainer(
    model         = model,
    tokenizer     = tokenizer,
    args          = sft_config,
    train_dataset = train_dataset,
    eval_dataset  = val_dataset,
)

print('✅ SFTTrainer configured and ready!')
print(f'   Train samples : {len(train_dataset):,}')
print(f'   Eval samples  : {len(val_dataset):,}')

import time

gpu_stats = torch.cuda.get_device_properties(0)
start_reserved = round(torch.cuda.max_memory_reserved() / 1024**3, 2)
max_memory     = round(gpu_stats.total_memory / 1024**3, 1)

print(f'GPU  : {gpu_stats.name}')
print(f'VRAM : {max_memory} GB total  |  {start_reserved} GB reserved before training')
print('=' * 60)
print('🚀 Starting fine-tuning from scratch (v3)...')
print('=' * 60)

start_time   = time.time()
train_result = trainer.train()  # fresh run — no checkpoint to resume
elapsed      = time.time() - start_time

peak_vram = round(torch.cuda.max_memory_reserved() / 1024**3, 2)
print('=' * 60)
print(f'✅ Training complete in {elapsed/60:.1f} minutes!')
print(f'   Final train loss : {train_result.training_loss:.4f}')
print(f'   Peak VRAM        : {peak_vram} GB / {max_memory} GB')

trainer.log_metrics('train', train_result.metrics)
trainer.save_metrics('train', train_result.metrics)

log_history  = trainer.state.log_history
train_losses = [(x['step'], x['loss'])      for x in log_history if 'loss' in x and 'eval_loss' not in x]
eval_losses  = [(x['step'], x['eval_loss']) for x in log_history if 'eval_loss' in x]

fig, ax = plt.subplots(figsize=(12, 5))

if train_losses:
    steps, losses = zip(*train_losses)
    ax.plot(steps, losses, label='Training Loss', color='#4A90D9', linewidth=2)

if eval_losses:
    steps, losses = zip(*eval_losses)
    ax.plot(steps, losses, label='Validation Loss', color='#E97040',
            linewidth=2, linestyle='--', marker='o', markersize=5)

ax.set_title('Training & Validation Loss — v3', fontsize=14, fontweight='bold')
ax.set_xlabel('Training Steps')
ax.set_ylabel('Loss')
ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('training_loss_v3.png', dpi=120)
plt.show()

if eval_losses:
    best_step, best_loss = min(eval_losses, key=lambda x: x[1])
    print(f'Best eval loss: {best_loss:.4f} at step {best_step}')

"""---
## ▶️ Section 7b — Resume Training from Checkpoint (if needed)

If your session crashed or you want to continue training, use the cell below.  
**Always pass `resume_from_checkpoint=` — never call `trainer.train()` bare on a loaded checkpoint.**
"""

# ── Only run this cell if you need to RESUME a crashed/partial run ──────────
# Do NOT run this after Section 7 completed successfully.

RESUME_CHECKPOINT = './medical_qa_mistral_lora_v3/checkpoint-500'  # ← change to your checkpoint

from unsloth import FastLanguageModel
import torch

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name     = RESUME_CHECKPOINT,
    max_seq_length = MAX_SEQ_LEN,
    dtype          = torch.bfloat16,
    load_in_4bit   = False,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token    = tokenizer.eos_token
    tokenizer.pad_token_id = tokenizer.eos_token_id

# Re-create trainer with same config (datasets must still be in memory)
trainer = SFTTrainer(
    model         = model,
    tokenizer     = tokenizer,
    args          = sft_config,
    train_dataset = train_dataset,
    eval_dataset  = val_dataset,
)

print(f'✅ Loaded checkpoint: {RESUME_CHECKPOINT}')
print('🔄 Resuming training (optimizer state + LR scheduler will be restored)...')

# CRITICAL: pass resume_from_checkpoint so scheduler/optimizer state are restored
train_result = trainer.train(resume_from_checkpoint=RESUME_CHECKPOINT)

print(f'✅ Resumed training complete!')
print(f'   Final train loss: {train_result.training_loss:.4f}')

"""---
## 💾 Section 8 — Save the Fine-Tuned Model
"""

SAVE_PATH = './medical_qa_mistral_lora_v3_final'

# Save LoRA adapters only (~100–200MB)
model.save_pretrained(SAVE_PATH)
tokenizer.save_pretrained(SAVE_PATH)

print(f'✅ LoRA adapters saved: {SAVE_PATH}')
for f in sorted(os.listdir(SAVE_PATH)):
    size = os.path.getsize(f'{SAVE_PATH}/{f}') / (1024 * 1024)
    print(f'   {f:<45} {size:.1f} MB')

# ── OPTIONAL: Merge LoRA weights into base model for standalone deployment ──
# Produces a full 14GB model you can load without PEFT

MERGED_PATH = './medical_qa_mistral_merged_v3'

print('Merging LoRA weights into base model (Unsloth fast merge)...')
model.save_pretrained_merged(
    MERGED_PATH,
    tokenizer,
    save_method = 'merged_16bit',  # Options: merged_16bit, lora, merged_4bit_forced
)
print(f'✅ Merged model saved: {MERGED_PATH}')

# ── OPTIONAL: Export to GGUF for Ollama / llama.cpp ──
# model.save_pretrained_gguf('./medical_qa_gguf', tokenizer, quantization_method='q4_k_m')

"""---
## 🩺 Section 9 — Inference & Testing
"""

FastLanguageModel.for_inference(model)
print('✅ Model switched to Unsloth inference mode (2× faster generation)')

def ask_medical_chatbot(question: str,
                        max_new_tokens: int = 512,
                        temperature: float = 0.3) -> str:
    """
    Ask the fine-tuned medical chatbot a question.

    Note: prompt format must exactly match training format — same system prompt,
    same [INST]...[/INST] template, NO MCQ options in the question.
    """
    prompt = (
        f'<s>[INST] {SYSTEM_PROMPT}\n\n'
        f'Question: {question} [/INST] '
    )

    inputs = tokenizer(
        prompt,
        return_tensors = 'pt',
        truncation     = True,
        max_length     = MAX_SEQ_LEN
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens     = max_new_tokens,
            temperature        = temperature,
            do_sample          = temperature > 0,
            top_p              = 0.9,
            repetition_penalty = 1.15,
            eos_token_id       = tokenizer.eos_token_id,
            pad_token_id       = tokenizer.pad_token_id,
            use_cache          = True,
        )

    full_output = tokenizer.decode(outputs[0], skip_special_tokens=True)
    answer = full_output.split('[/INST]')[-1].strip()
    return answer


print('✅ Inference function ready!')

test_questions = [
    'What are the early warning signs of Type 2 Diabetes?',
    'What is the difference between systolic and diastolic blood pressure?',
    'Can you explain what a myocardial infarction is and its common symptoms?',
    'What medications are commonly used to treat hypertension?',
    'What are the risk factors for developing Alzheimer\'s disease?',
]

print('🩺 Medical Q&A Chatbot — Test Results (v3)')
print('=' * 70)

for i, question in enumerate(test_questions, 1):
    print(f'\n[Q{i}] {question}')
    print('-' * 60)
    answer = ask_medical_chatbot(question)
    print(f'[A]  {answer}')
    print()

# ── Interactive Medical Q&A Cell ─────────────────────────────────────────────
# Run this cell, type your question in the input box, press Enter or click Ask

import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

question_box = widgets.Textarea(
    placeholder='e.g. What are the symptoms of Type 2 Diabetes?',
    layout=widgets.Layout(width='100%', height='80px')
)

ask_btn = widgets.Button(
    description='Ask',
    button_style='primary',
    layout=widgets.Layout(width='100px')
)

clear_btn = widgets.Button(
    description='Clear',
    button_style='',
    layout=widgets.Layout(width='100px')
)

output = widgets.Output()

def on_ask(b):
    question = question_box.value.strip()
    if not question:
        return
    with output:
        clear_output()
        display(HTML("<p style='color:gray; font-size:13px'>⏳ Generating answer...</p>"))
        answer = ask_medical_chatbot(question, max_new_tokens=512, temperature=0.3)
        clear_output()
        display(HTML(f"""
            <div style='border-left: 3px solid #4A90D9; padding: 10px 16px; margin: 8px 0; border-radius: 4px; background: #f4f8fd;'>
                <p style='font-weight:600; margin: 0 0 6px; color:#1a1a1a;'>Q: {question}</p>
                <p style='margin: 0; color:#2c2c2c; line-height:1.7;'>A: {answer}</p>
            </div>
            <p style='font-size:11px; color:gray; margin-top:6px;'>
                ⚠️ For research purposes only. Not a substitute for professional medical advice.
            </p>
        """))

def on_clear(b):
    question_box.value = ''
    with output:
        clear_output()

ask_btn.on_click(on_ask)
clear_btn.on_click(on_clear)

display(HTML("<h4 style='margin-bottom:8px;'>🩺 Medical Q&A — Interactive Test</h4>"))
display(widgets.HBox([ask_btn, clear_btn]))
display(question_box)
display(output)

!pip install rouge-score

!pip install bert-score

import warnings
import transformers
transformers.logging.set_verbosity_error()

from rouge_score import rouge_scorer
import numpy as np

scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)

sample = df_val.sample(100, random_state=42)
scores = {'rouge1': [], 'rouge2': [], 'rougeL': []}

for _, row in sample.iterrows():
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        pred = ask_medical_chatbot(row['question'], max_new_tokens=256)
    result = scorer.score(row['answer'], pred)
    for k in scores:
        scores[k].append(result[k].fmeasure)

print("ROUGE Scores (on 100 val samples):")
for k, v in scores.items():
    print(f"  {k}: {np.mean(v):.4f}")

# pip install bert-score
from bert_score import score as bert_score

preds, refs = [], []
sample = df_val.sample(100, random_state=42)
for _, row in sample.iterrows():
    preds.append(ask_medical_chatbot(row['question'], max_new_tokens=256))
    refs.append(row['answer'])

P, R, F1 = bert_score(preds, refs, lang='en', verbose=False)
print(f"BERTScore — Precision: {P.mean():.4f} | Recall: {R.mean():.4f} | F1: {F1.mean():.4f}")

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np

def plot_score_distributions(rouge_scores, bert_f1_scores):
    """
    rouge_scores: dict with keys 'rouge1', 'rouge2', 'rougeL' — lists of F1 floats
    bert_f1_scores: list of BERTScore F1 floats (from bert_score output tensor → .tolist())
    """
    metrics = {
        'ROUGE-1': (rouge_scores['rouge1'], '#4A90D9'),
        'ROUGE-2': (rouge_scores['rouge2'], '#E97040'),
        'ROUGE-L': (rouge_scores['rougeL'], '#2ECC71'),
        'BERTScore F1': (bert_f1_scores,    '#9B59B6'),
    }

    fig = plt.figure(figsize=(18, 10))
    fig.suptitle('Score Distributions — 100 Val Samples', fontsize=15, fontweight='bold', y=0.98)
    gs = gridspec.GridSpec(2, 4, figure=fig, hspace=0.45, wspace=0.35)

    # ── Row 1: histograms ──────────────────────────────────────────────────
    for col, (name, (vals, color)) in enumerate(metrics.items()):
        ax = fig.add_subplot(gs[0, col])
        ax.hist(vals, bins=15, color=color, alpha=0.75, edgecolor='white')
        ax.axvline(np.mean(vals),   color='black',  linestyle='--', lw=1.5, label=f'mean={np.mean(vals):.3f}')
        ax.axvline(np.median(vals), color='dimgray', linestyle=':',  lw=1.5, label=f'med={np.median(vals):.3f}')
        ax.set_title(name, fontsize=12, fontweight='bold')
        ax.set_xlabel('F1 score', fontsize=10)
        ax.set_ylabel('Count', fontsize=10)
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.25)
        ax.set_xlim(0, 1)

    # ── Row 2: box plot + summary table ───────────────────────────────────
    ax_box = fig.add_subplot(gs[1, :3])
    data   = [v for v, _ in metrics.values()]
    colors = [c for _, c in metrics.values()]
    bp = ax_box.boxplot(data, patch_artist=True, notch=False,
                        medianprops=dict(color='black', linewidth=2))
    for patch, color in zip(bp['boxes'], colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.65)
    for flier, color in zip(bp['fliers'], colors):
        flier.set(marker='o', markerfacecolor=color, markersize=4, alpha=0.6)

    ax_box.set_xticks(range(1, 5))
    ax_box.set_xticklabels(list(metrics.keys()), fontsize=11)
    ax_box.set_ylabel('F1 score', fontsize=11)
    ax_box.set_ylim(0, 1.05)
    ax_box.set_title('Box plot comparison', fontsize=12, fontweight='bold')
    ax_box.grid(True, axis='y', alpha=0.25)

    # ── Summary stats table ────────────────────────────────────────────────
    ax_tbl = fig.add_subplot(gs[1, 3])
    ax_tbl.axis('off')
    rows = []
    for name, (vals, _) in metrics.items():
        rows.append([
            name,
            f'{np.mean(vals):.3f}',
            f'{np.std(vals):.3f}',
            f'{np.percentile(vals, 25):.3f}',
            f'{np.median(vals):.3f}',
            f'{np.percentile(vals, 75):.3f}',
        ])
    tbl = ax_tbl.table(
        cellText=rows,
        colLabels=['Metric', 'Mean', 'Std', 'Q1', 'Med', 'Q3'],
        loc='center', cellLoc='center'
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(9)
    tbl.scale(1.1, 1.8)
    ax_tbl.set_title('Summary stats', fontsize=11, fontweight='bold', pad=10)

    plt.savefig('score_distributions.png', dpi=130, bbox_inches='tight')
    plt.show()
    print('✅ Saved: score_distributions.png')


# ── Call it right after your eval loops ───────────────────────────────────────
plot_score_distributions(
    rouge_scores={'rouge1': scores['rouge1'], 'rouge2': scores['rouge2'], 'rougeL': scores['rougeL']},
    bert_f1_scores=F1.tolist()   # F1 tensor from bert_score()
)

"""
--------------------------------------------------------------------
Section 10 — Hugging Face Export (Removed for Public Repository)
--------------------------------------------------------------------

This section was removed before publishing to GitHub to avoid
credential exposure and accidental access leaks.

--------------------------------------------------------------------
"""

"""---
## 📋 Summary — v2 → v3 Changes

| Component | v2 (broken / suboptimal) | v3 (fixed) |
|---|---|---|
| **Install** | `git+github` (CUDA mismatch risk) | Auto-detect CUDA → correct wheel |
| **MedAlpaca format** | MCQ options in question → inference mismatch | MCQ options stripped, answer prefix removed |
| **MAX_SEQ_LEN** | 512 (truncates answers) | 2048 |
| **Token filter** | 512 (too aggressive) | 1500 est tokens |
| **packing** | False (padding waste) | True (3-4× more tokens/step) |
| **lora_alpha** | 128 (2× rank → over-scales) | 64 (= rank) |
| **lora_dropout** | 0.05 | 0.0 (Unsloth-optimised) |
| **use_rslora** | False | True |
| **Effective batch** | 16 | 32 |
| **Checkpoint resume** | `trainer.train()` bare (scheduler resets) | `resume_from_checkpoint=` |
| **dtype** | Auto (may pick wrong) | Explicit `torch.bfloat16` |

### ⚠️ Medical Disclaimer
> This model is for research and educational purposes only.  
> **Never deploy as a substitute for professional medical advice.**
"""